import type { Metadata } from 'next';
import { LegalDocument } from '@/components/LegalDocument';

export const metadata: Metadata = {
  title: 'Disclaimer | TradeVision AI',
  description: 'Review the important trading, financial, and AI usage disclaimers for TradeVision AI.',
};

export default function DisclaimerPage() {
  return (
    <LegalDocument
      eyebrow="Legal"
      title="Disclaimer"
      intro="TradeVision AI provides AI-generated chart analysis and market observations for informational and educational workflow support only. The content made available through the platform is not investment, legal, tax, accounting, or financial advice."
      effectiveDate="March 22, 2026"
      sections={[
        {
          title: 'No Financial Advice',
          content: (
            <>
              <p>No analysis, commentary, projected entry, stop loss, take profit, confidence score, trend label, or model output available on TradeVision AI should be treated as a recommendation to buy, sell, hold, or manage any security, derivative, currency, index, synthetic instrument, or other financial product.</p>
              <p>You are solely responsible for evaluating any trading decision, confirming market information independently, and obtaining professional advice where appropriate.</p>
            </>
          ),
        },
        {
          title: 'Market Risk Warning',
          content: (
            <>
              <p>Trading and investing involve substantial risk and may result in partial or total loss of capital. Leveraged products and highly volatile instruments can increase the speed and magnitude of losses. Past performance, backtesting assumptions, or historical chart structure do not guarantee future results.</p>
              <p>Any use of TradeVision AI should be combined with independent judgment, sound risk management, and awareness of your personal objectives, experience, and risk tolerance.</p>
            </>
          ),
        },
        {
          title: 'AI and Data Limitations',
          content: (
            <>
              <p>AI systems may produce incomplete, delayed, inaccurate, inconsistent, or misleading outputs. Results may vary based on chart quality, timeframe selection, uploaded imagery, provider availability, model changes, and platform limitations. Service outputs should always be reviewed critically before being relied upon.</p>
              <p>TradeVision AI does not warrant that any analysis is correct, current, executable, profitable, or suitable for live market conditions.</p>
            </>
          ),
        },
        {
          title: 'Third-Party Platforms and Instruments',
          content: (
            <>
              <p>References to third-party brokers, charting tools, exchanges, trading platforms, or instrument names are made for compatibility and descriptive purposes only. TradeVision AI is not responsible for third-party pricing feeds, execution quality, outages, terms, platform rules, or product structures.</p>
              <p>Your relationship with any broker, exchange, or payment provider remains subject to that third party&apos;s own agreements and disclosures.</p>
            </>
          ),
        },
        {
          title: 'User Responsibility',
          content: (
            <>
              <p>By using TradeVision AI, you acknowledge that you assume full responsibility for your interpretation and use of any output generated by the platform. You agree not to rely exclusively on the service when making financial decisions and accept the risks inherent in market activity and AI-assisted analysis tools.</p>
            </>
          ),
        },
      ]}
    />
  );
}